name: Release

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'
      - '.github/workflows/release.yml'

jobs:
  release:
    permissions:
      contents: write
      packages: write
      id-token: write
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Configure npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          npm config set access public

      - name: Build packages
        run: yarn build

      - name: Test packages
        run: yarn test
      
      - name: Detect changed packages
        id: changed_packages
        run: |
          # Create a JSON array of packages
          PACKAGES_JSON=$(find packages -type f -name "package.json" -not -path "*/node_modules/*" | 
                          grep -o 'packages/[^/]*' | 
                          sort | 
                          uniq | 
                          jq -R -s -c 'split("\n")[:-1]')
          echo "packages=$PACKAGES_JSON" >> $GITHUB_OUTPUT
          
          # Also create a space-separated list for shell usage
          CHANGED_PACKAGES=$(find packages -type f -name "package.json" -not -path "*/node_modules/*" | 
                            grep -o 'packages/[^/]*' | 
                            sort | 
                            uniq)
          
          # Format for summary
          echo "## Packages to be released" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          for PKG in $CHANGED_PACKAGES; do
            echo "- $PKG" >> $GITHUB_STEP_SUMMARY
          done
          echo "" >> $GITHUB_STEP_SUMMARY
      
      - name: Setup Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Release with semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHANGED_PACKAGES: ${{ steps.changed_packages.outputs.packages }}
        run: |
          # Convert JSON array back to space-separated list for shell processing
          PACKAGES_LIST=$(echo '${{ steps.changed_packages.outputs.packages }}' | jq -r 'join(" ")')
          
          # Release each changed package
          RELEASE_SUMMARY=""
          for PKG in $PACKAGES_LIST; do
            echo "Publishing package: $PKG"
            cd $PKG
            
            # Get current version
            CURRENT_VERSION=$(node -p "require('./package.json').version")
            
            # Check if .releaserc.json exists, create if not
            if [ ! -f .releaserc.json ]; then
              echo "Creating .releaserc.json from template"
              cp ../../.github/release-template.json .releaserc.json
            fi
            
            # For test-utils package, handle 0.x versioning 
            if [[ "$PKG" == "packages/test-utils" ]]; then
              # Check if package exists on npm yet
              PACKAGE_EXISTS=$(npm view @xava-labs/test-utils version 2>/dev/null || echo "")
              
              if [[ -z "$PACKAGE_EXISTS" ]]; then
                # If package doesn't exist yet, force first release at 0.1.0
                npm version 0.1.0 --no-git-tag-version --allow-same-version
                echo "First-time publishing test-utils at version 0.1.0"
                RELEASE_OUTPUT=$(npx semantic-release --branches main --no-ci --first-release 2>&1 || true)
              else
                # Get existing versions
                PREV_RELEASE=$(npm view @xava-labs/test-utils versions --json 2>/dev/null || echo "[]")
                
                # Determine if we need to bump minor or patch based on commit history
                BUMP_TYPE=$(npx semantic-release --dry-run --branches main 2>&1 | grep -o "The next release version is" | wc -l)
                
                if [[ $BUMP_TYPE -gt 0 ]]; then
                  # Get the recommended bump type based on commits
                  NEXT_VERSION_TYPE=$(npx semantic-release --dry-run --branches main 2>&1 | grep -o "release type: \\w\\+" | cut -d " " -f 3)
                  
                  # Current version components
                  CURRENT_MAJOR=$(echo $CURRENT_VERSION | cut -d. -f1)
                  CURRENT_MINOR=$(echo $CURRENT_VERSION | cut -d. -f2)
                  CURRENT_PATCH=$(echo $CURRENT_VERSION | cut -d. -f3)
                  
                  # Calculate next version
                  if [[ "$NEXT_VERSION_TYPE" == "major" ]]; then
                    # For a major bump in 0.x, we increment the minor instead (0.x.y -> 0.[x+1].0)
                    NEXT_MINOR=$((CURRENT_MINOR + 1))
                    NEXT_VERSION="0.$NEXT_MINOR.0"
                  elif [[ "$NEXT_VERSION_TYPE" == "minor" ]]; then
                    # For a minor bump in 0.x, we also increment the minor (0.x.y -> 0.[x+1].0)
                    NEXT_MINOR=$((CURRENT_MINOR + 1))
                    NEXT_VERSION="0.$NEXT_MINOR.0"
                  else
                    # For a patch bump, increment patch (0.x.y -> 0.x.[y+1])
                    NEXT_PATCH=$((CURRENT_PATCH + 1))
                    NEXT_VERSION="0.$CURRENT_MINOR.$NEXT_PATCH"
                  fi
                  
                  # Set this version in package.json
                  npm version $NEXT_VERSION --no-git-tag-version --allow-same-version
                  echo "Bumping test-utils version to $NEXT_VERSION based on semantic-release recommendation"
                  RELEASE_OUTPUT=$(npx semantic-release --branches main --no-ci 2>&1 || true)
                else
                  # No changes requiring version bump
                  echo "No changes detected requiring version bump for test-utils"
                  RELEASE_OUTPUT="No changes requiring release detected"
                fi
              fi
            # For MCP package, correctly handle versioning
            elif [[ "$PKG" == "packages/mcp" ]]; then
              # Check if package exists on npm yet
              PACKAGE_EXISTS=$(npm view @xava-labs/mcp version 2>/dev/null || echo "")
              
              if [[ -z "$PACKAGE_EXISTS" ]]; then
                # If package doesn't exist yet, determine if we want to start at 1.0.0 or 0.1.0
                if [[ "$CURRENT_VERSION" == 1.* ]]; then
                  npm version 1.0.0 --no-git-tag-version --allow-same-version
                  echo "First-time publishing mcp at version 1.0.0"
                else 
                  npm version 0.1.0 --no-git-tag-version --allow-same-version
                  echo "First-time publishing mcp at version 0.1.0"
                fi
                RELEASE_OUTPUT=$(npx semantic-release --branches main --no-ci --first-release 2>&1 || true)
              else
                # Get existing versions
                PREV_RELEASE=$(npm view @xava-labs/mcp versions --json 2>/dev/null || echo "[]")
                
                # Determine if we need to bump version based on commit history
                BUMP_TYPE=$(npx semantic-release --dry-run --branches main 2>&1 | grep -o "The next release version is" | wc -l)
                
                if [[ $BUMP_TYPE -gt 0 ]]; then
                  # Get the recommended bump type based on commits
                  NEXT_VERSION_TYPE=$(npx semantic-release --dry-run --branches main 2>&1 | grep -o "release type: \\w\\+" | cut -d " " -f 3)
                  
                  # Current version components
                  CURRENT_MAJOR=$(echo $CURRENT_VERSION | cut -d. -f1)
                  CURRENT_MINOR=$(echo $CURRENT_VERSION | cut -d. -f2)
                  CURRENT_PATCH=$(echo $CURRENT_VERSION | cut -d. -f3)
                  
                  # Calculate next version properly depending on current major version
                  if [[ "$CURRENT_MAJOR" == "0" ]]; then
                    # For 0.x versions
                    if [[ "$NEXT_VERSION_TYPE" == "major" || "$NEXT_VERSION_TYPE" == "minor" ]]; then
                      # For a major or minor bump in 0.x, increment the minor (0.x.y -> 0.[x+1].0)
                      NEXT_MINOR=$((CURRENT_MINOR + 1))
                      NEXT_VERSION="0.$NEXT_MINOR.0"
                    else
                      # For a patch bump, increment patch (0.x.y -> 0.x.[y+1])
                      NEXT_PATCH=$((CURRENT_PATCH + 1))
                      NEXT_VERSION="0.$CURRENT_MINOR.$NEXT_PATCH"
                    fi
                  else
                    # For 1.x and above, follow standard semver
                    if [[ "$NEXT_VERSION_TYPE" == "major" ]]; then
                      NEXT_MAJOR=$((CURRENT_MAJOR + 1))
                      NEXT_VERSION="$NEXT_MAJOR.0.0"
                    elif [[ "$NEXT_VERSION_TYPE" == "minor" ]]; then
                      NEXT_MINOR=$((CURRENT_MINOR + 1))
                      NEXT_VERSION="$CURRENT_MAJOR.$NEXT_MINOR.0"
                    else
                      NEXT_PATCH=$((CURRENT_PATCH + 1))
                      NEXT_VERSION="$CURRENT_MAJOR.$CURRENT_MINOR.$NEXT_PATCH"
                    fi
                  fi
                  
                  # Set this version in package.json
                  npm version $NEXT_VERSION --no-git-tag-version --allow-same-version
                  echo "Bumping mcp version to $NEXT_VERSION based on semantic-release recommendation"
                  RELEASE_OUTPUT=$(npx semantic-release --branches main --no-ci 2>&1 || true)
                else
                  # No changes requiring version bump
                  echo "No changes detected requiring version bump for mcp"
                  RELEASE_OUTPUT="No changes requiring release detected"
                fi
              fi
            # If version starts with 0, force semantic-release to respect that  
            elif [[ "$CURRENT_VERSION" == 0.* ]]; then
              # Use dryRun first to determine the next version
              NEXT_VERSION=$(npx semantic-release --dry-run --branches main 2>&1 | grep -oP 'The next release version is \K[0-9]+\.[0-9]+\.[0-9]+' || echo "")
              
              if [[ -n "$NEXT_VERSION" ]]; then
                # Now modify package.json to have a version that's one less than the determined version
                MAJOR=$(echo $NEXT_VERSION | cut -d. -f1)
                MINOR=$(echo $NEXT_VERSION | cut -d. -f2)
                PATCH=$(echo $NEXT_VERSION | cut -d. -f3)
                
                if [[ $PATCH -gt 0 ]]; then
                  PATCH=$((PATCH - 1))
                elif [[ $MINOR -gt 0 ]]; then
                  MINOR=$((MINOR - 1))
                  PATCH=9
                else
                  MAJOR=$((MAJOR - 1))
                  MINOR=9
                  PATCH=9
                fi
                
                PREV_VERSION="$MAJOR.$MINOR.$PATCH"
                
                # Update package.json with one version behind
                npm version $PREV_VERSION --no-git-tag-version
                echo "Setting version to $PREV_VERSION to force next version as $NEXT_VERSION"
                
                # Run semantic-release
                RELEASE_OUTPUT=$(npx semantic-release --branches main 2>&1 || true)
              else
                # Fallback if can't determine next version
                RELEASE_OUTPUT=$(npx semantic-release --branches main 2>&1 || true)
              fi
            # For all other packages, use standard semantic-release
            else
              echo "Processing standard package with version $CURRENT_VERSION"
              RELEASE_OUTPUT=$(npx semantic-release --branches main 2>&1 || true)
            fi
            echo "$RELEASE_OUTPUT"
            
            # Extract new version if available
            if echo "$RELEASE_OUTPUT" | grep -q "Publishing version"; then
              NEW_VERSION=$(echo "$RELEASE_OUTPUT" | grep "Publishing version" | sed -E 's/.*Publishing version ([0-9]+\.[0-9]+\.[0-9]+).*/\1/')
              echo "Successfully published $PKG@$NEW_VERSION (was $CURRENT_VERSION)"
              RELEASE_SUMMARY="$RELEASE_SUMMARY\n### $PKG\n- Published: v$NEW_VERSION (was v$CURRENT_VERSION)\n"
            else
              echo "No new version to release for $PKG"
              RELEASE_SUMMARY="$RELEASE_SUMMARY\n### $PKG\n- No release needed (current: v$CURRENT_VERSION)\n"
            fi
            
            cd ../../
          done
          
          # Output summary
          echo -e "$RELEASE_SUMMARY" >> $GITHUB_STEP_SUMMARY
      
      - name: Output release status
        run: |
          echo "✅ Release process completed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Packages have been published to npm." >> $GITHUB_STEP_SUMMARY 